### PR TITLE
updated conda metadata

### PR DESCRIPTION
**Pull request by gh-ppolk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@gh-ppolk, this is nice to have.  It's important to follow the instructions, though, bumping the build number and rerendering the recipe.  Otherwise, the changes won't take effect until the next PR that actually makes those changes.

**Comment by davidism** [comment]
Sorry @xylar, we were doing this during a PyCon sprint and it was our first time figuring out how these worked. @gh-ppolk made similar PRs for the other Pallets projects. They've already been merged, should we make new PRs to bump the build number?

- MarkupSafe https://github.com/conda-forge/markupsafe-feedstock/pull/28
- ItsDangerous https://github.com/conda-forge/itsdangerous-feedstock/pull/16
- Werkzeug https://github.com/conda-forge/werkzeug-feedstock/pull/32
- Jinja https://github.com/conda-forge/jinja2-feedstock/pull/31
- Click https://github.com/conda-forge/click-feedstock/pull/42

It looks like the "rerender" command comment wasn't made on some of them either.

**Comment by xylar** [comment]
@davidism, no, that's fine.  It's just that you will find that the changes don't take immediate effect.  But the next time those feedstocks get updated (with a new release or a dependency change) that's when the changes will actually happen.

**Comment by davidism** [comment]
That might be very unlikely or slow in some cases, such as for ItsDangerous and MarkupSafe.

**Comment by xylar** [comment]
There would be no harm in doing a second PR to bump the build number and rerender.

**Pull request merged**
