### PR TITLE
Add noarch python and modified the script build

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Add the noarch: python to save time in the CI and also update the build script to follow the best approach for conda as described in the documentation.

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge-admin, please re-render.

**Comment by marcelotrevisani** [comment]
@nehaljwani maybe I have to rerun the ```re-render``` because I didn't see your comment before of my ```push --force```.  I will try it. But thanks to remember me

**Comment by marcelotrevisani** [comment]
@conda-forge-admin, please re-render.

**Comment by marcelotrevisani** [comment]
@nehaljwani , Could you please review that for me?

**Pull request merged**
